In [19]:
import pandas as pd

In [20]:
staff_df = pd.DataFrame([{'Name': 'Kelly', 'Role': 'Director of HR'},
                         {'Name': 'Sally', 'Role': 'Course liasion'},
                         {'Name': 'James', 'Role': 'Grader'}])

staff_df = staff_df.set_index('Name')

student_df = pd.DataFrame([{'Name': 'James', 'School': 'Business'},
                           {'Name': 'Mike', 'School': 'Law'},
                           {'Name': 'Sally', 'School': 'Engineering'}])

student_df = student_df.set_index('Name')

In [21]:
student_df

            School
Name
James     Business
Mike           Law
Sally  Engineering

In [22]:
staff_df

                 Role
Name
Kelly  Director of HR
Sally  Course liasion
James          Grader

In [23]:
# Set Union
pd.merge(staff_df, student_df, how='outer', left_index=True, right_index=True)

                 Role       School
Name
James          Grader     Business
Kelly  Director of HR          NaN
Mike              NaN          Law
Sally  Course liasion  Engineering

In [24]:
# Set Intersection
pd.merge(staff_df, student_df, how='inner', left_index=True, right_index=True)

                 Role       School
Name
Sally  Course liasion  Engineering
James          Grader     Business

In [25]:
# Only the first table but if have any extra information prints them
pd.merge(staff_df, student_df, how='left', left_index=True, right_index=True)

                 Role       School
Name
Kelly  Director of HR          NaN
Sally  Course liasion  Engineering
James          Grader     Business

In [26]:
# Only the second table but if have any extra information prints them
pd.merge(staff_df, student_df, how='right', left_index=True, right_index=True)

                 Role       School
Name
James          Grader     Business
Mike              NaN          Law
Sally  Course liasion  Engineering

In [27]:
staff_df = staff_df.reset_index()
student_df = student_df.reset_index()

pd.merge(staff_df, student_df, how='right', on='Name')

    Name            Role       School
0  James          Grader     Business
1   Mike             NaN          Law
2  Sally  Course liasion  Engineering