In [15]:
import pandas as pd

In [27]:
df_2009 = pd.read_csv("datasets/college-scorecard/MERGED2009_10_PP.csv", low_memory=False)
df_2010 = pd.read_csv("datasets/college-scorecard/MERGED2010_11_PP.csv", low_memory=False)
df_2012 = pd.read_csv("datasets/college-scorecard/MERGED2012_13_PP.csv", low_memory=False)

In [28]:
df_2010.head(3)

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMAWDP8_NOTFIRSTTIME_POOLED_SUPP,OMENRUP_NOTFIRSTTIME_POOLED_SUPP,OMENRYP_FULLTIME_POOLED_SUPP,OMENRAP_FULLTIME_POOLED_SUPP,OMAWDP8_FULLTIME_POOLED_SUPP,OMENRUP_FULLTIME_POOLED_SUPP,OMENRYP_PARTTIME_POOLED_SUPP,OMENRAP_PARTTIME_POOLED_SUPP,OMAWDP8_PARTTIME_POOLED_SUPP,OMENRUP_PARTTIME_POOLED_SUPP
0,100654,00100200,1002,Alabama A & M University,Normal,AL,35762,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100663,00105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100690,02503400,25034,Amridge University,Montgomery,AL,36117-3553,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
print(len(df_2010))
print(len(df_2009))
print(len(df_2012))

7414
7149
7793

In [30]:
frames = [df_2009, df_2010, df_2012]
pd.concat(frames)

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMAWDP8_NOTFIRSTTIME_POOLED_SUPP,OMENRUP_NOTFIRSTTIME_POOLED_SUPP,OMENRYP_FULLTIME_POOLED_SUPP,OMENRAP_FULLTIME_POOLED_SUPP,OMAWDP8_FULLTIME_POOLED_SUPP,OMENRUP_FULLTIME_POOLED_SUPP,OMENRYP_PARTTIME_POOLED_SUPP,OMENRAP_PARTTIME_POOLED_SUPP,OMAWDP8_PARTTIME_POOLED_SUPP,OMENRUP_PARTTIME_POOLED_SUPP
0,100654,00100200,1002,Alabama A & M University,Normal,AL,35762,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100663,00105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100690,02503400,25034,Amridge University,Montgomery,AL,36117-3553,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100706,00105500,1055,University of Alabama in Huntsville,Huntsville,AL,35899,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100724,00100500,1005,Alabama State University,Montgomery,AL,36104-0271,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7788,47691101,4205801,42058,SAE Institute of Technology San Francisco,Emeryville,CA,94608,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7789,47701101,10145905,1459,Strayer University-Bloomington Campus,Bloomington,MN,554311411,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7790,47702001,10145903,1459,Strayer University-Schaumburg Campus,Schaumburg,IL,601735081,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7791,47702002,10145902,1459,Strayer University-Downers Grove Campus,Downers Grove,IL,605151169,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7792,47702003,10145906,1459,Strayer University-Aurora Campus,Aurora,IL,605066220,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
pd.concat(frames, keys=['2011','2012','2013'])

             UNITID     OPEID  OPEID6  \
2011 0       100654  00100200    1002
     1       100663  00105200    1052
     2       100690  02503400   25034
     3       100706  00105500    1055
     4       100724  00100500    1005
...             ...       ...     ...
2013 7788  47691101   4205801   42058
     7789  47701101  10145905    1459
     7790  47702001  10145903    1459
     7791  47702002  10145902    1459
     7792  47702003  10145906    1459

                                              INSTNM           CITY STABBR  \
2011 0                      Alabama A & M University         Normal     AL
     1           University of Alabama at Birmingham     Birmingham     AL
     2                            Amridge University     Montgomery     AL
     3           University of Alabama in Huntsville     Huntsville     AL
     4                      Alabama State University     Montgomery     AL
...                                              ...            ...    ...
2013 7788  SAE Institute of Technology San Francisco     Emeryville     CA
     7789      Strayer University-Bloomington Campus    Bloomington     MN
     7790       Strayer University-Schaumburg Campus     Schaumburg     IL
     7791    Strayer University-Downers Grove Campus  Downers Grove     IL
     7792           Strayer University-Aurora Campus         Aurora     IL

                  ZIP  ACCREDAGENCY  INSTURL  NPCURL  ...  \
2011 0          35762           NaN      NaN     NaN  ...
     1     35294-0110           NaN      NaN     NaN  ...
     2     36117-3553           NaN      NaN     NaN  ...
     3          35899           NaN      NaN     NaN  ...
     4     36104-0271           NaN      NaN     NaN  ...
...               ...           ...      ...     ...  ...
2013 7788       94608           NaN      NaN     NaN  ...
     7789   554311411           NaN      NaN     NaN  ...
     7790   601735081           NaN      NaN     NaN  ...
     7791   605151169           NaN      NaN     NaN  ...
     7792   605066220           NaN      NaN     NaN  ...

           OMAWDP8_NOTFIRSTTIME_POOLED_SUPP  OMENRUP_NOTFIRSTTIME_POOLED_SUPP  \
2011 0                                  NaN                               NaN
     1                                  NaN                               NaN
     2                                  NaN                               NaN
     3                                  NaN                               NaN
     4                                  NaN                               NaN
...                                     ...                               ...
2013 7788                               NaN                               NaN
     7789                               NaN                               NaN
     7790                               NaN                               NaN
     7791                               NaN                               NaN
     7792                               NaN                               NaN

           OMENRYP_FULLTIME_POOLED_SUPP  OMENRAP_FULLTIME_POOLED_SUPP  \
2011 0                              NaN                           NaN
     1                              NaN                           NaN
     2                              NaN                           NaN
     3                              NaN                           NaN
     4                              NaN                           NaN
...                                 ...                           ...
2013 7788                           NaN                           NaN
     7789                           NaN                           NaN
     7790                           NaN                           NaN
     7791                           NaN                           NaN
     7792                           NaN                           NaN

           OMAWDP8_FULLTIME_POOLED_SUPP  OMENRUP_FULLTIME_POOLED_SUPP  \
2011 0                              NaN                           NaN
     1                              NaN                           NaN
     2                              NaN                           NaN
     3                              NaN                           NaN
     4                              NaN                           NaN
...                                 ...                           ...
2013 7788                           NaN                           NaN
     7789                           NaN                           NaN
     7790                           NaN                           NaN
     7791                           NaN                           NaN
     7792                           NaN                           NaN

           OMENRYP_PARTTIME_POOLED_SUPP  OMENRAP_PARTTIME_POOLED_SUPP  \
2011 0                              NaN                           NaN
     1                              NaN                           NaN
     2                              NaN                           NaN
     3                              NaN                           NaN
     4                              NaN                           NaN
...                                 ...                           ...
2013 7788                           NaN                           NaN
     7789                           NaN                           NaN
     7790                           NaN                           NaN
     7791                           NaN                           NaN
     7792                           NaN                           NaN

           OMAWDP8_PARTTIME_POOLED_SUPP  OMENRUP_PARTTIME_POOLED_SUPP
2011 0                              NaN                           NaN
     1                              NaN                           NaN
     2                              NaN                           NaN
     3                              NaN                           NaN
     4                              NaN                           NaN
...                                 ...                           ...
2013 7788                           NaN                           NaN
     7789                           NaN                           NaN
     7790                           NaN                           NaN
     7791                           NaN                           NaN
     7792                           NaN                           NaN

[22356 rows x 1977 columns]